### PR TITLE
MA-3750/ Create Global CloudTrail for new customers

### PR DESCRIPTION
**Pull request by mayankbharadwaj**
Purpose : 

Currently we are enabling cloudtrail in every region for new customer in the onboarding process but now create Global CloudTrail for new customers in the onboarding state machine flow.

Changes : 

-  Modified the index file by adding multiRegion parameter.

### CODE REVIEW

**Review by bhargavapratik — CHANGES_REQUESTED** [review]
This is wrong place to add this muliRegion , this is the list function and not create. 
Just uncomment line 48 to create global cloudtrail.

**Review by SonalOjha — APPROVED** [review]
LGTM

**Review by RajkumarShivage — APPROVED** [review]
LGTM

**Review by bhargavapratik — APPROVED** [review]

**Comment by bhargavapratik** [comment]
LGTM

**Review by SonalOjha — APPROVED** [review]
LGTM

**Review by SonalOjha — APPROVED** [review]
LGTM

**Review by bhargavapratik — APPROVED** [review]

**Comment by mayankbharadwaj** [comment]
@bhargavapratik addressed your commets

**Pull request merged**
